"""Static analysis of a 16 MB A100 PCIe 80GB BAR0 dump.

Reads a 16 MB raw BAR0 image (the kind you get from
``dd if=/sys/bus/pci/devices/0000:01:00.0/resource0 of=/tmp/dump.bin``)
and produces a structured report:

  * Family A range (0x110000-0x113000): non-zero registers
  * Family B range (0x120000-0x123000): non-zero registers
  * Family A vs cmpunlocker 10GB CMP baseline: diffs
  * Family B vs cmpunlocker 10GB CMP baseline: diffs (the 80GB candidates)
  * Suggested cfg1/lmr candidates (heuristic ranking)
  * 0xbadf5040 / 0xbadf1100 / 0xbadf1300 (NVIDIA debug-marker) — never
    actual 80GB values, just markers
  * Reserved / write-protected ranges

The output is a YAML report ready to be pasted into a
constants.yaml or handed to whoever has root on a CMP 170HX.

Usage:
    python3 -m tools.a100_register_report a100-0000_01_00_0-bar0-16m.bin
"""

import argparse
import os
import struct
import sys


# cmpunlocker's documented 10GB CMP live values at 0000:01:00.0.
# These come from constants.yaml notes; they're the 10GB reference.
CMP_10GB_LIVE = {
    0x110000: 0x10,
    0x110040: 0,
    0x110044: 0,
    0x110048: 0x1004,
    0x11004c: 0x100002,
    0x110060: 0x8000,
    0x110094: 0,
    0x1100d8: 0,
    0x1100dc: 0,
    0x1100e0: 0,
    0x1100e8: 0,
    0x1100ec: 0,
    0x1100f0: 0,
    0x1100f4: 0,
    0x1100f8: 0,
    0x1100fc: 0,
    0x110200: 0,
    0x110208: 0x30c003,
    0x110240: 0x7000,
    0x110244: 0x40000000,
    0x110250: 0x0f,
    0x110268: 0x100,
    0x11026c: 0x3f,
    0x110274: 0x100,
    0x110278: 0x1000100,
    0x11027c: 0xff,
    0x110280: 0x88,
    0x110284: 0xff,
    0x110288: 0x8f,
    0x11028c: 0xff,
    0x110290: 0xff,
    0x110294: 0xff,
    0x110298: 0x8f,
    0x11029c: 0xff,
    0x1102c0: 0xffffffff,
    0x1102c4: 0xffffffff,
    0x1102c8: 0xffffffff,
    0x1102cc: 0xffffffff,
    0x1102e4: 0x7fffffff,
    0x1102e8: 0xffffffff,
    0x110600: 0,
    0x110604: 0,
    0x110608: 0,
    0x11060c: 0,
    0x110610: 0,
    0x110614: 0,
    0x110618: 0,
    0x11061c: 0,
    0x110620: 0,
    0x110624: 0x90,
    0x110628: 0x1400,
    0x11062c: 0x80000064,
    0x110630: 0x2440c142,
    0x110638: 0xa1a02726,
    0x110660: 0x20000,
    0x110670: 0xff,
    0x110674: 0x0f,
    0x110684: 1,
    0x110688: 0xff,
    0x110690: 0x830086a8,
    0x110694: 0x07008583,
    0x120040: 0,
    0x120044: 0,
    0x120048: 0x53,
    0x12004c: 0,
    0x120050: 1,
    0x120054: 0xbadf5040,
    0x120058: 0,
    0x12005c: 0,
    0x120060: 0,
    0x120064: 0xce6,
    0x12006c: 0x10,
    0x120070: 0x100001,
    0x120074: 0x08,
    0x120078: 0x05,
    0x122110: 0,
    0x122114: 0,
    0x122118: 0,
    0x122120: 0,
    0x122128: 0,
    0x122134: 0,
    0x122138: 0,
    0x12213c: 0,
    0x12214c: 0,
    0x122150: 0,
    0x122154: 0,
    0x122158: 0,
    0x12215c: 0,
    0x122160: 0,
    0x122164: 0,
    0x122168: 0,
    0x12216c: 0,
    0x122170: 0,
    0x122174: 0,
    0x122178: 0,
    0x12217c: 0,
    0x1221ec: 0,
    0x1221f0: 0,
    0x1221f4: 0,
    0x122200: 0,
    0x122204: 2,
    0x12221c: 0,
}

# NVIDIA debug markers — never actual values, just firmware-scratch.
NVIDIA_DEBUG_MARKERS = (0xbadf5040, 0xbadf1100, 0xbadf1300)


def is_marker(val):
    return any((val & m) == m for m in NVIDIA_DEBUG_MARKERS)


def load_bar0(path):
    with open(path, 'rb') as f:
        return f.read()


def dump_range(data, lo, hi, step=4, cmp10gb=None, label='?'):
    """Return list of (addr, value) where value != 0, with diff vs cmp10gb."""
    out = []
    for off in range(lo, hi, step):
        if off + 4 > len(data):
            break
        val = struct.unpack_from('<I', data, off)[0]
        if val != 0:
            cmp_v = cmp10gb.get(off, None) if cmp10gb else None
            differs = (cmp_v is not None and cmp_v != val)
            out.append((off, val, cmp_v, differs))
    return out


def report_yaml(out, dump_path):
    """Pretty-print the report in YAML for constants.yaml consumption."""
    fam_a_entries = out['fam_a']
    fam_b_entries = out['fam_b']
    diffs = out['diffs']

    print('# generated by tools.a100_register_report')
    print(f'# source: {dump_path}')
    print('# analysis: Family-A & Family-B non-zero registers + diffs vs cmpunlocker 10GB CMP')
    print()
    print('bar0_dump_summary:')
    print(f'  source_file: {os.path.basename(dump_path)}')
    print(f'  size_bytes: {os.path.getsize(dump_path)}')
    print(f'  family_a_nonzero_count: {len(fam_a_entries)}')
    print(f'  family_b_nonzero_count: {len(fam_b_entries)}')
    print(f'  diffs_from_10gb_cmp: {len(diffs)}')
    print()
    print('# === Family A (0x110000-0x113000) — non-zero registers ===')
    for off, val, cmp_v, differs in fam_a_entries:
        flag = ' ← DIFFERS from 10GB CMP' if differs else ''
        cmp_str = f' (10GB was 0x{cmp_v:08x})' if cmp_v is not None else ''
        marker = '  ← NVIDIA debug marker' if is_marker(val) else ''
        print(f'  - {{addr: 0x{off:06x}, value: 0x{val:08x}}}{cmp_str}{flag}{marker}')
    print()
    print('# === Family B (0x120000-0x123000) — non-zero registers ===')
    for off, val, cmp_v, differs in fam_b_entries:
        flag = ' ← DIFFERS from 10GB CMP' if differs else ''
        cmp_str = f' (10GB was 0x{cmp_v:08x})' if cmp_v is not None else ''
        marker = '  ← NVIDIA debug marker' if is_marker(val) else ''
        print(f'  - {{addr: 0x{off:06x}, value: 0x{val:08x}}}{cmp_str}{flag}{marker}')
    print()
    print('# === cfg1/lmr candidates (sorted by diff-size, biggest diff first) ===')
    diffs_sorted = sorted(diffs, key=lambda d: -abs((d[1] or 0) - (d[2] or 0)))
    for off, val, cmp_v, _ in diffs_sorted:
        if cmp_v is not None:
            print(f'  - {{addr: 0x{off:06x}, value: 0x{val:08x}, 10gb_was: 0x{cmp_v:08x}, delta: 0x{val - cmp_v:+x}}}')


def main(argv=None):
    p = argparse.ArgumentParser(
        prog='a100_register_report',
        description='Static analysis of a 16MB A100 80GB BAR0 dump',
    )
    p.add_argument('dump', help='Path to 16MB raw BAR0 image (e.g. a100-0000_01_00_0-bar0-16m.bin)')
    p.add_argument('--no-yaml', action='store_true',
                   help='Just print human-readable, skip YAML output')
    args = p.parse_args(argv)

    if not os.path.isfile(args.dump):
        sys.exit(f'ERROR: {args.dump} not found')

    data = load_bar0(args.dump)
    if len(data) < 1024 * 1024:
        sys.exit(f'ERROR: dump is only {len(data)} bytes, expected ~16 MB')

    fam_a = dump_range(data, 0x110000, 0x113000, cmp10gb=CMP_10GB_LIVE, label='Family A')
    fam_b = dump_range(data, 0x120000, 0x123000, cmp10gb=CMP_10GB_LIVE, label='Family B')

    # combined diffs (both families)
    diffs = [(o, v, c, d) for o, v, c, d in fam_a + fam_b if d]
    diffs.sort(key=lambda x: x[0])

    out = {'fam_a': fam_a, 'fam_b': fam_b, 'diffs': diffs}

    if not args.no_yaml:
        report_yaml(out, args.dump)
    else:
        print(f'=== Family A non-zero: {len(fam_a)} ===')
        for off, val, _, _ in fam_a:
            print(f'  +0x{off:06x} = 0x{val:08x}')
        print()
        print(f'=== Family B non-zero: {len(fam_b)} ===')
        for off, val, _, _ in fam_b:
            print(f'  +0x{off:06x} = 0x{val:08x}')
        print()
        print(f'=== Diffs vs 10GB CMP: {len(diffs)} ===')
        for off, val, cmp_v, _ in diffs:
            print(f'  +0x{off:06x}: 10GB=0x{cmp_v:08x} → 80GB=0x{val:08x}')


if __name__ == '__main__':
    main()
