"""Generate 80GB-candidate writes from a booter_emu sweep.

Runs the Falcon emulator across a programmed sweep of ``fuse_value_0x7ca``
values. Each unique BAR0-write stream is intersected against Family A
and Family B address ranges. The result is a YAML snippet suitable for
appending to ``common/constants.yaml`` (manually).

The values reported are *emulator-derived*: they depend on an
approximate DMA/fuse model and may not match the real A100 firmware's
writes. Treat them as PROBES, not authoritatives. Verify on real
hardware using ``try_memory_unlock_candidates()`` in
``unlock/memory.py``.

Usage:
    python3 -m tools.candidate_summary /lib/firmware/nvidia/580.159.03/gsp_tu10x.bin
"""

import argparse
import os
import sys

# Make ``tools.foo`` importable when the script is invoked as
# ``python3 tools/candidate_summary.py``.
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from booter_emu import (  # noqa: E402
    FalconBooter,
    diff_writes,
    extract_booter_sections,
    summarize_writes,
)


# Programmed sweep — covers bit-0, bit-7, mid-range, all-ones, and
# "human-looking" fuse patterns an A100 might emit.
DEFAULT_SWEEP = [
    0,
    1,
    2,
    4,
    8,
    16,
    32,
    0x80,
    0xff,
    0x100,
    0x1000,
    0xff00,
    0xffff,
    0x10000,
    0x100000,
    0xdeadbeef,
    0xfeedface,
]


def _emit_yaml(family, sweeps, runs, max_steps):
    print(f'# generated by tools.candidate_summary (max-steps={max_steps})')
    print(f'# — these writes diverge between fuse sweeps — NOT verified')
    print()
    for fam_name, lo, hi in (('a', 0x110000, 0x113000),
                              ('b', 0x120000, 0x123000)):
        family_addrs = set()
        for sw in sweeps:
            for _, (va_val, _, _) in runs:
                pass  # unused — see below
        # diffs: list of (addr, list of [(fuse, value), ...]) across all
        # pairs that produce a divergence.
        family_emit = []
        for f_a in sweeps:
            for f_b in sweeps:
                if f_a >= f_b:
                    continue
                _, w_a = runs[f_a]
                _, w_b = runs[f_b]
                diffs = diff_writes(w_a, w_b)
                for addr, va, vb in diffs:
                    if lo <= addr < hi:
                        family_emit.append((addr, f_a, f_b, va, vb))

        if not family_emit:
            continue
        print(f'{fam_name}_geometry_emulator_candidates:')
        # group by address
        by_addr = {}
        for addr, f_a, f_b, va, vb in family_emit:
            by_addr.setdefault(addr, []).append((f_a, va, f_b, vb))

        for addr in sorted(by_addr):
            entries = by_addr[addr]
            va_set = {e[1] for e in entries}
            vb_set = {e[3] for e in entries}
            print(f'  # diff candidates at 0x{addr:06x}')
            print(f'  - addr: 0x{addr:06x}')
            if len(va_set) <= 1 and len(vb_set) <= 1:
                # all sweeps agree this address has two possible values
                va_ex = entries[0][1]
                vb_ex = entries[0][3]
                if va_ex is None:
                    print(f'    value_when_size_match: null')
                else:
                    print(f'    value_when_size_match: 0x{va_ex:x}')
                if vb_ex is None:
                    print(f'    value_when_size_diverges: null')
                else:
                    print(f'    value_when_size_diverges: 0x{vb_ex:x}')
            else:
                print(f'    value_set: [{", ".join(f"0x{v:x}" for v in sorted({x for x in va_set | vb_set if x is not None}))}]')
            print()


def main(argv=None):
    p = argparse.ArgumentParser(
        prog='candidate_summary',
        description='Diff two emulator runs and produce Family-A/B YAML',
    )
    p.add_argument('firmware')
    p.add_argument('--fuse-a', default='0')
    p.add_argument('--fuse-b', required=True,
                   help='Compare against this fuse (e.g. 0xdeadbeef for an A100-like signature)')
    p.add_argument('--max-steps', type=int, default=200_000)
    p.add_argument('--family', choices=('a', 'b', 'all'), default='all')
    p.add_argument('--min-fuses', type=int, default=3,
                   help='Report only addresses produced by >= N fuses. Default 3 '
                        '(filters out single-bit heuristic artifacts).')
    args = p.parse_args(argv)

    secs = extract_booter_sections(args.firmware)
    if not secs:
        raise SystemExit(f'no .ga100_* sections found in {args.firmware}')

    fuses_to_try = DEFAULT_SWEEP + [int(args.fuse_b, 16)]
    runs = {}
    for f in fuses_to_try:
        emu = FalconBooter(secs, fuse_value_0x7ca=f, max_steps=args.max_steps)
        emu.run()
        runs[f] = (emu, emu.bar0_writes)
        print(f'fuse=0x{f:08x}: {len(emu.bar0_writes)} writes, {len(summarize_writes(emu.bar0_writes))} distinct',
              file=sys.stderr)

    # Collect Family-A/B addresses produced with ≥ N fuses
    fam_a = (0x110000, 0x113000)
    fam_b = (0x120000, 0x123000)
    addr_writes = {}
    for _, writes in runs.values():
        s = summarize_writes(writes)
        for a, vs in s.items():
            if fam_a[0] <= a < fam_a[1] or fam_b[0] <= a < fam_b[1]:
                addr_writes.setdefault(a, set()).add(vs[-1])

    print()
    print(f'# Minimum fuses to report: {args.min_fuses}')
    for fam_name, lo, hi in (('A (0x110000-0x112fff)', fam_a[0], fam_a[1]),
                              ('B (0x120000-0x122fff)', fam_b[0], fam_b[1])):
        print()
        print(f'# === FAMILY {fam_name} ===')
        any_in_fam = False
        for a in sorted(addr_writes):
            if not (lo <= a < hi):
                continue
            if len(addr_writes[a]) < args.min_fuses:
                continue
            any_in_fam = True
            print(f'0x{a:06x}  writes={sorted(addr_writes[a])}')
        if not any_in_fam:
            print('(no candidates above noise threshold)')

    return 0


if __name__ == '__main__':
    sys.exit(main())
